name: FabiolaBenavente
favicon: null
layout_spectrum: 0.3283340747002512
typography_spectrum: 0.6503956781234592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6794297089800239
  lightness: 0.3710175266023725
  saturation: 0.791427344083786
  rhythmicContrast: 0.5813775160349905
purpose: []
